version: '3.4'

services:
  php:
    container_name: sylius.php
    build:
      context: .
      target: sylius_php
    image: php:latest
    depends_on:
      - mysql
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=EDITME
      - DATABASE_URL=mysql://sylius:root@mysql/sylius
      - MAILER_URL=smtp://mailhog:1025
      - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
    volumes:
      - .:/srv/sylius:rw,cached
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./var:/srv/sylius/var:rw
      - ./public:/srv/sylius/public:rw,delegated
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./public/media:/srv/sylius/public/media:rw
      - public-media:/srv/sylius/public/media:rw

  ## MYSQL ##
  mysql:
    container_name: sylius.mysql
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=sylius
      - MYSQL_USER=sylius
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-root}
    volumes:
      - mysql-data:/var/lib/mysql:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/mysql/data:/var/lib/mysql:rw,delegated
    ports:
      - "3308:3306"

  ## ADMINER ##
  adminer:
    container_name: sylius.adminer
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DESIGN=nette
    restart: always
    ports:
      - 8888:8080
    depends_on:
      - mysql

  ## NODE ##
  node:
    container_name: sylius.node
    build:
      context: .
      target: sylius_node
      # Quay does not work, should be replaced in future with f.e. ghcr.io
      # cache_from:
      #   - quay.io/sylius/php:latest
      #   - quay.io/sylius/nodejs:latest
      #   - quay.io/sylius/nginx:latest
    image: node:latest
    depends_on:
      - php
    environment:
      - GULP_ENV=dev
      - PHP_HOST=php
      - PHP_PORT=9000
    volumes:
      - .:/srv/sylius:rw,cached
      - ./public:/srv/sylius/public:rw,delegated
    ports:
      - "35729:35729"

  ## NGINX ##
  nginx:
    container_name: sylius.nginx
    build:
      context: .
      target: sylius_nginx
    image: nginx:latest
      # Quay does not work, should be replaced in future with f.e. ghcr.io
      # cache_from:
      #   - quay.io/sylius/php:latest
      #   - quay.io/sylius/nodejs:latest
      #   - quay.io/sylius/nginx:latest
    depends_on:
      - php
      - node # to ensure correct build order
    volumes:
      - ./public:/srv/sylius/public:ro
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./public/media:/srv/sylius/public/media:ro
      - public-media:/srv/sylius/public/media:ro,nocopy
    ports:
      - "80:80"

  ## MAILHOG ##
  mailhog:
    container_name: sylius.mailhog
    # do not use in production!
    image: mailhog/mailhog:latest
    environment:
      - MH_STORAGE=maildir
    # volumes:
    #   - ./docker/mailhog/maildir:/maildir:rw,delegated
    ports:
      - "8025:8025"

volumes:
  mysql-data:
  public-media:
